id: I37F623FD
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 15:19:38.683489+00:00
last_modified: 2022-12-14 15:19:38.683495+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-049-001
  eft-text-version: 1.0.4 2021
  title: Toh_106-Unravelling_the_Intent-v2
bases:
  27AE:
    source_metadata: null
    order: 1
    base_file: 27AE.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
